### ISSUE TITLE
Level Design

### ISSUE THREAD

**Issue by Nirase** [Nirase/Spelmotordriven-produktutveckling-HT21#117]
## Definition of done
- [x] Three key locations
   - [x] Lighthouse
   - [x] #123
   - [x] #131

Extra:
- [ ] Minor areas (on hold)
- [ ] Final Area (on hold)
   - [ ] Large tree that gains more features as colours are unlocked (on hold=
- [ ] Rough draft of the entire world (on hold)
