### ISSUE TITLE
Project Plan Update (End of production)

### ISSUE THREAD

**Issue by Nirase** [Nirase/Spelmotordriven-produktutveckling-HT21#187]
## Definition of done
- [x] FMod instead of Wwise
- [x] Markdown instead of google drive
- [x] Information about production planning
