### ISSUE TITLE
GDD

### ISSUE THREAD

**Issue by Nirase** [Nirase/Spelmotordriven-produktutveckling-HT21#2]
## Definition of done
- [x] Version List
- [x] General description of goal
- [x] General description of gameplay
- [x] General description of world
- [x] General  description of story
- [x] Technical Specs
- [x] Target Audience
- [ ] Detailed description of story
- [ ] Detailed description of plot
- [ ] Detailed description of characters 
- [ ] Detailed description of ending(s)
- [ ] Concept art and initial art used
- [x] Detailed description of mechanics
- [ ] Detailed description of dynamics
- [ ] Detailed description of rules
- [ ] Detailed description of start/end conditions
- [ ] Design of the interface and the controls
- [ ] Levels designed
- [ ] Detailed description of the tool
