### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by Nirase** [Nirase/Spelmotordriven-produktutveckling-HT21#3]
- [x] Version list
- [x] Team composition: members and roles
- [x] Time plan, including phases with planned deliverables and deadlines for all team members
- [x] Technical requirements for all aspects of the projects (which tools are used and what for, including version control, team management, communication, and documentation)
- [x] Methodology: planned meetings and sprints, goals for the meetings and sprints. 
- [x] Risk analysis: description of potential risks, sorted by importance, and ways to overcome them.
