### ISSUE TITLE
Move GDD and Project Plan into repo

### ISSUE THREAD

**Issue by DannyDarwiche** [Nirase/Spelmotordriven-produktutveckling-HT21#66]
### Description
Up until now our documentation has been handled in Google Drive. We are moving our documentation to the GitHub repo so we can centralize our project and connect our documentation updates to issues.

### Definition of done
- [x] Project plan moved into /docs
- [x] Game design document moved into /docs
- [x] All documents use the markdown format
