### ISSUE TITLE
End of Pre-Production Build

### ISSUE THREAD

**Issue by Nirase** [Nirase/Spelmotordriven-produktutveckling-HT21#97]
## Definition of done
- [x] Showcases all the things we have created
- [x] Pattern Recognition
   - [x] Follow a set path
   - [x] Follow a set pattern but not necessarily a set path
- [x] AIs
   - [x] Chase
   - [x] Follow
   - [x] Guiding
   - [x] Boids
   - [x] Avoid
- [x] Weather
   - [x] Snow
   - [x] Rain
   - [x] Wind
- [x] Shaders
   - [x] Ice Trails
   - [x] Snow
   - [x] Ice
   - [x] Corrosion
   - [x] Water
   - [x] Water Ripples
   - [x] Fish
   - [x] Color Adding 
- [x] Controllers
   - [x] Rigidbody WASD
- [x] Menus
   - [x] Pause Menu
   - [x] Settings Menu
- [x] Animations
